# Until https://github.com/julia-actions/julia-uploadcodecov/issues/1 get fixed
# submit coverage report via travis
language: julia

os:
  - linux

julia:
  - 1.0

notifications:
  email: false

script:
  - julia --check-bounds=yes --color=yes --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true);'

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
